### ISSUE TITLE
amazing work

### ISSUE THREAD

**Issue by Kimeiga** [alexandersandberg/html5-elements-tester#13]
I was recently looking for a larger compilation of html elements than cbracco's and found this, and it even has <ruby> which I only recently learned about. This makes me want to make Bahunya actually not terrible since I see you included it (and kacit HAHAH). 

I would suggest including new.css, it's actually far better than mine, and I'm sure it will look good.

Cheers! :))

**Comment by Kimeiga** [comment]
![image](https://user-images.githubusercontent.com/20587215/152450711-81b99a4e-08db-4c84-a6e1-e6e5b3c50e6f.png)
actually it looks like it might not look that good after all haha

**Comment by alexandersandberg** [comment]
Hey! Feel free to open a PR with suggested changes if you want. 🙂

**Comment by Kimeiga** [comment]
Hey Alexander, I overhauled Bahunya heavily and I think it looks much more professional. However, I noticed that the navigation on your site has two rows of links, so I will try to fix this in Bahunya, thanks for building this haha

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/20587215/173994778-463f6629-35e1-44b8-a66b-b0efd4e477bb.png">
